prod:
    hostname:      do
    user:          root
    identity_file: ~
    deploy_path:   /var/www/Polidog.Todo
    repository:    https://github.com/koriym/Polidog.Todo.git
    branch:        deploy
    dotenv:        .env.prod
    context:       prod-html-app
    appname:       Polidog\Todo

stage:
    hostname:      do
    user:          root
    identity_file: ~
    deploy_path:   /var/www/Polidog.Todo
    repository:    https://github.com/koriym/Polidog.Todo.git
    branch:        master
    dotenv:        .env.stage
    context:       html-app
    appname:       Polidog\Todo
